version: "3"

tasks:
    winres:
        desc: Compile windows resources
        cmds:
            - go-winres.exe make
        sources:
            - winres/**/*

    build:
        desc: Build the project
        deps: [winres]
        cmds:
            - go build -o vye.exe

    release:
        cmds:
            - go build -trimpath -ldflags "-s -w -H=windowsgui" -o vye.exe
